# Generated by Django 4.1.5 on 2023-01-27 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Matches",
            fields=[
                (
                    "match_id",
                    models.IntegerField(
                        db_index=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="match_id",
                    ),
                ),
                ("season", models.IntegerField(verbose_name="season")),
                ("city", models.CharField(max_length=255, verbose_name="city")),
                ("date", models.DateField(max_length=10, verbose_name="date")),
                ("team1", models.CharField(max_length=255, verbose_name="team1")),
                ("team2", models.CharField(max_length=255, verbose_name="team2")),
                (
                    "toss_winner",
                    models.CharField(max_length=255, verbose_name="toss_winner"),
                ),
                (
                    "toss_decision",
                    models.CharField(max_length=10, verbose_name="toss_decision"),
                ),
                ("result", models.CharField(max_length=10, verbose_name="result")),
                ("dl_applied", models.IntegerField(verbose_name="dl_applied")),
                ("winner", models.CharField(max_length=255, verbose_name="winner")),
                ("win_by_runs", models.IntegerField(verbose_name="win_by_runs")),
                ("win_by_wickets", models.IntegerField(verbose_name="win_by_wickets")),
                (
                    "player_of_match",
                    models.CharField(max_length=255, verbose_name="player_of_match"),
                ),
                ("venue", models.CharField(max_length=255, verbose_name="venue")),
                ("umpire1", models.CharField(max_length=255, verbose_name="umpire1")),
                ("umpire2", models.CharField(max_length=255, verbose_name="umpire2")),
                (
                    "umpire3",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="umpire3"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deliveries",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        db_index=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                ("inning", models.IntegerField(verbose_name="inning")),
                (
                    "batting_team",
                    models.CharField(max_length=255, verbose_name="batting_team"),
                ),
                (
                    "bowling_team",
                    models.CharField(max_length=255, verbose_name="bowling_team"),
                ),
                ("over", models.IntegerField(verbose_name="over")),
                ("ball", models.IntegerField(verbose_name="ball")),
                ("batsman", models.CharField(max_length=255, verbose_name="batsman")),
                (
                    "non_striker",
                    models.CharField(max_length=255, verbose_name="non_striker"),
                ),
                ("bowler", models.CharField(max_length=255, verbose_name="bowler")),
                ("is_super_over", models.IntegerField(verbose_name="is_super_over")),
                ("wide_runs", models.IntegerField(verbose_name="wide_runs")),
                ("bye_runs", models.IntegerField(verbose_name="bye_runs")),
                ("legbye_runs", models.IntegerField(verbose_name="legbuy_runs")),
                ("noball_runs", models.IntegerField(verbose_name="noball_runs")),
                ("penalty_runs", models.IntegerField(verbose_name="penalty_runs")),
                ("batsman_runs", models.IntegerField(verbose_name="batsman_runs")),
                (
                    "extra_runs",
                    models.IntegerField(default=0, verbose_name="extra_runs"),
                ),
                ("total_runs", models.IntegerField(verbose_name="total_runs")),
                (
                    "player_dismissed",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="player_dismissed",
                    ),
                ),
                (
                    "dismissal_kind",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="dismissal_kind",
                    ),
                ),
                (
                    "fielder",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="fielder"
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ipl.matches",
                    ),
                ),
            ],
        ),
    ]
